name: CI-demo

# This workflow is triggered on pushes and pull requests to the repository.
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: | # Add the command to run your tests here
        echo "Run your tests here"
